### ISSUE TITLE
Error when trying to download Sentinel images for negative longitudes

### ISSUE THREAD

**Issue by t-boo** [olivierhagolle/Sentinel-download#19]
I am trying to download Sentinel images over the UK using the command:
python Sentinel_download.py --lat 52.192620 --lon -2.239065 -a apihub.txt -d 2016-01-01 -s S2

It results in the error message "IndexError: list index out of range" from line 281 in Sentinel_Download.py. It appears to be the negative longitude value that is causing the troubles, since it works flawlessly when using positive longitude values. I have also tried with specifying --latmin and --lonmin, with the same result.

**Comment by GertS** [comment]
Thank you for reporting this bug. It was a coincidence that it didn't work with negative longitude values. The cause of the problem was that the ESA scihub now delivers also stand-alone tile products. This script wasn't ready for that. I created a pull request to fix this bug.

**Comment by t-boo** [comment]
Thank you Gert. The new version of the script works with negative longitude values.
