### ISSUE TITLE
Change needed in lines 351, and some others

### ISSUE THREAD

**Issue by ognjenantonijevic** [olivierhagolle/Sentinel-download#22]
For the new product format " **or names[i].find('MSIL1C')>0** " needs to be added to if clause.
And also I think " **.replace("eu/odata","eu/apihub/odata")** " is no longer required, since they have corrected the urls.

**Comment by olivierhagolle** [comment]
Thanks for suggestions, and sorry for taking so long. This works fine.
Olivier
