### ISSUE TITLE
NOT AN ISSUE, But a doubt

### ISSUE THREAD

**Issue by GonzaloFrontec** [olivierhagolle/Sentinel-download#26]
Hello Olivier! my question is next, I am trying to get a query of all available images of S2 for a point, it works correctly but the latest image is missing, ie, (did it on 19/Jul) for point lon -61.52651 lat -35.76756  I get that the las available is 2017-06-16 but in the site If I check the same spot I get that the last is on 2017-07-06 and I could not find on the Sentinel site anything about it. 

Let me know if you have some clue about it.

Thanks!

Gonzalo

**Comment by GertS** [comment]
I think you mixed up the latitude and longitude coordinates. Try to swap the two coordinates.

**Comment by GonzaloFrontec** [comment]
@GertS thank you for the response, but those coordinates are ok.

**Comment by GertS** [comment]
I am sorry, the coordinates are indeed correct. However I can not reproduce your problem, I used this command:
`./Sentinel_download.py -n --lat -35.76756 --lon -61.52651 --apihub_passwd apihub.txt --start_date 20170601`
Resulting in exactly the same images as on the website.

**Comment by GonzaloFrontec** [comment]
Hello GertS, I can't reproduce it too. I must have been some sort of update database from sentinel hub.

Thanks.
