### ISSUE TITLE
Sentinel 2B not downloading 

### ISSUE THREAD

**Issue by GonzaloFrontec** [olivierhagolle/Sentinel-download#28]
Hello Olivier, I was wondering if it is an issue or it is how it should work, but the script does not query Sentinel 2 B images.

Thanks,

Gonzalo

**Comment by olivierhagolle** [comment]
Hi Gonzalo,
I lack time, and I have not worked much on this script, I am using the peps_download.py script now, also in my github (https://github.com/olivierhagolle/peps_download). Peps is a global mirror site, it has S2B already, a few minutes after copernicus hub.

S2B is not yet in the official sentinel-hub, it is on a pre-operational site.  I did not work on it, yet, sorry.
Feel free to add it !
Olivier

**Comment by GonzaloFrontec** [comment]
Hello Olivier,
Thank you very much for your quick answer, I will look at peps. I ask you know if you area aware of the potential date for Sentinel 2B data to be on operational mode?.

Thanks again,

Gonzalo

**Comment by olivierhagolle** [comment]
ESA says mid-september (https://sentinel.esa.int/web/sentinel/missions/sentinel-2/mission-status). It should be coming soon
Olivier

**Comment by GonzaloFrontec** [comment]
Thank you very much.

Kind regards,

Gonzalo

2017-09-10 5:06 GMT-03:00 Olivier Hagolle <notifications@github.com>:
