### ISSUE TITLE
I am new to Sentinel-downlowd, wget is not recogniced as internal command? I run this python script though anaconda with jupyter notebook and python 2.7 on win machine.

### ISSUE THREAD

**Issue by vak000** [olivierhagolle/Sentinel-download#38]
wget --no-check-certificate  --user="guest" --password="guest" --output-document=query_results.xml "https://scihub.copernicus.eu/apihub/search?q=footprint:"Intersects(POLYGON((-23.0 51.75, 23.75 51.75, 23.75 52.25, -23.0 52.25,-23.0 51.75)))" filename:S1A*GRDH*&rows=100"

'wget' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "Sentinel_download.py", line 279, in <module>
    xml = minidom.parse("query_results.xml")
  File "C:\Users\vaak\AppData\Local\conda\conda\envs\gdal\lib\xml\dom\minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "C:\Users\vaak\AppData\Local\conda\conda\envs\gdal\lib\xml\dom\expatbuilder.py", line 922, in parse
    fp = open(file, 'rb')
IOError: [Errno 2] No such file or directory: 'query_results.xml'

**Comment by olivierhagolle** [comment]
Hi,
this tool is not meant to work on windows, although it might. Anyway, you will need to install wget
Olivier
