### ISSUE TITLE
S1 bug?

### ISSUE THREAD

**Issue by pkolokoussis** [olivierhagolle/Sentinel-download#39]
I use the script to automatically download S1 and S2 data (thank you for sharing). When downloading S2 data everything is fine. When downloading S1 data, the script seems to interpret Lat(min,max) and Long(min,max) in reverse, Lat for Long and Long for Lat.

**Comment by olivierhagolle** [comment]
Thanks for the feedback.
Well, on my side, the request is passed exactly in the same way for S1 and S2, and I can't imagine ESA's interface works in a different way for both sensors.

```
https://scihub.copernicus.eu/apihub/search?q=footprint:%22Intersects(POLYGON((1.44%2043.6,%201.6%2043.6,%201.6%2043.8,%201.44%2043.8,1.44%2043.6)))%22%20filename:S2B*&rows=100
```
```
 https://scihub.copernicus.eu/apihub/search?q=footprint:%22Intersects(POLYGON((1.44%2043.6,%201.6%2043.6,%201.6%2043.8,%201.44%2043.8,1.44%2043.6)))%22%20filename:S1B*&rows=100
```
 I don't use this script too much these days, and replaced it by peps_download (also on my github, the download goes to PEPS, the french collaborative ground segment)

**Comment by pkolokoussis** [comment]
Yes, you are absolutely right, the two xml's perform the same request when I use the script. For some strange reason, at least in my case, ESA's api systematically interprets lat and long in reverse for S1*SLC or S1*GRD. I will investigate it further...  Thanks!

**Comment by olivierhagolle** [comment]
Thanks, 
Please tell me if you get information about it
Regards,
Olivier
