### ISSUE TITLE
compatibility for OSX

### ISSUE THREAD

**Issue by umwilm** [olivierhagolle/Sentinel-download#4]
Hi Oliver, not really an issue, a suggestion:

extending line 193 with checking for darwin, makes the script compatible for OSX as well:
193: if sys.platform.startswith('linux') or sys.platform.startswith('darwin'):

cheers, Uwe

**Comment by olivierhagolle** [comment]
Hi Uwe,
I have added it on each line in which there was a If Linux, but I did not test.
If ever you find some time to test it, please tell me.
But I guess SEN2COR keeps you busy...
Olivier

**Comment by umwilm** [comment]
yes, we will release a big update within the next days, which should solve a lot of the issues reported. I keep you informed.

Thanks and cheers,
Uwe
________________________________

**Comment by umwilm** [comment]
Hi Olivier,

I found another issue. The ECMWF metadata in the AUX_DATA in each granule are a file, containing the OZONE content. But the downloader creates a directory instead. Probably as it has no extension. A possible workaround could be as:

Line 43 ff.

for i in range(len(urls)):
    if types[i] == 'Item' and not 'ECMWFT' in names[i]:

Then it will be downloaded properly.

Have a nice Sunday,

Cheers,
Uwe

________________________________

**Comment by olivierhagolle** [comment]
Thanks a lot Uwe. 
I corrected this error and pushed the new version. It must be a windows system which distributes the data and needs an extension to recognize a directory.
Best regards,
Olivier
