### ISSUE TITLE
Extension to cover bulk downloads of Sentinel 3

### ISSUE THREAD

**Issue by dtlloyd** [olivierhagolle/Sentinel-download#41]
Hi,

Thanks for sharing this repository. I really liked your code for bulk downloading Landsat data as well.

Do you have any plans to make this code compatible with Sentinel 3 data?

**Comment by olivierhagolle** [comment]
Thanks for the comment. 
I am not a Sentinel3 user, and I will probably not find time to do it, sorry. 
But if some one added it, that would be nice ;)
Olivier

**Comment by dtlloyd** [comment]
Thanks for your reply Oliver.

For those who would like to bulk download Sentinel 3 data through Python, I have found the [SentinelSat library](https://github.com/sentinelsat/sentinelsat) works quite well.
