### ISSUE TITLE
switch wget to aria

### ISSUE THREAD

**Issue by unnic** [olivierhagolle/Sentinel-download#7]
Hello,

I'm trying to run Sentinel-download on my windows machine. 
When I try python `Sentinel_download.py --lat 43.6 --lon 1.44 -a apihub.txt -o 51 -s S2` i get an error `query_results.xml not found` and `wget is not recognized as an internal or external command`
 
Do I have to change anything if I want to use aria2 instead of wget?

**Comment by olivierhagolle** [comment]
Hi Unnic,

You should first install wget or aria2 on your computer. If you choose to use aria2, then you'll have to use the following option :  
--downloader aria2

Be aware that as I am working on linux and never on windows, I don't test the module on windows. It relies on the tests of other users. For instance some users say that  the following lines are working, some others recommend to use the linux syntax even for windows.  So in case you have any difficulty, remove the tests on the platform. It might work... and please tell us if you succeeded.

Best regards,
Olivier


    if sys.platform.startswith('linux') or sys.platform.startswith('darwin'):
        query_geom='footprint:\\"Intersects(%f,%f)\\"'%(options.lat,options.lon)
    else :
        query_geom='footprint:"Intersects(%f,%f)"'%(options.lat,options.lon)
	
elif geom=='rectangle':
    if sys.platform.startswith('linux') or sys.platform.startswith('darwin'):
        query_geom='footprint:\\"Intersects(POLYGON(({lonmin} {latmin}, {lonmax} {latmin}, {lonmax} {latmax}, {lonmin} {latmax},{lonmin} {latmin})))\\"'.format(latmin=options.latmin,latmax=options.latmax,lonmin=options.lonmin,lonmax=options.lonmax)
    else :
        query_geom='footprint:"Intersects(POLYGON(({lonmin} {latmin}, {lonmax} {latmin}, {lonmax} {latmax}, {lonmin} {latmax},{lonmin} {latmin})))"'.format(latmin=options.latmin,latmax=options.latmax,lonmin=options.lonmin,lonmax=options.lonmax)
