### ISSUE TITLE
Empty .xml files  for S2A download

### ISSUE THREAD

**Issue by wouellette** [olivierhagolle/Sentinel-download#9]
Hi Olivier,

I am experiencing problems with downloading S2A data on a per tile basis (-t). All elements of the .SAFE folder are downloading fine, but the general .xml file in the root of the S2A image .SAFE folder is completely blank. This is the case for all S2A images I am trying to download. I tried typing in the url link to the server in my browser to download the .xml manually, and an "error 404 not found" shows up. 

Here is the command I use (linux CentOS): 
python Sentinel_download.py --lat 50.42 --lon 6.02 -a apihub.txt -w /data -o 8  -t 31UES

Could it be that the the location of the .xml file on scihub has changed and the link that your script points to is outdated?

Thanks for you script in any case, a life saver :)

Regards,

William

**Comment by olivierhagolle** [comment]
Thanks William,
i am in holidays with a very poor wify. Will try that when I am back.
Olivier
________________________________________
De : wouellette [notifications@github.com]
Envoy� : vendredi 15 juillet 2016 11:27
� : olivierhagolle/Sentinel-download
Objet : [olivierhagolle/Sentinel-download] Empty .xml files for S2A download (#9)

Hi Olivier,

I am experiencing problems with downloading S2A data on a per tile basis (-t). All elements of the .SAFE folder are downloading fine, but the general .xml file in the root of the S2A image .SAFE folder is completely blank. This is the case for all S2A images I am trying to download. I tried typing in the url link to the server in my browser to download the .xml manually, and an "error 404 not found" shows up.

Here is the command I use (linux CentOS):
python Sentinel_download.py --lat 50.42 --lon 6.02 -a apihub.txt -w /data -o 8 -t 31UES

Could it be that the the location of the .xml file on scihub has changed and the link that your script points to is outdated?

Thanks for you script in any case, a life saver :)

Regards,

William

�

**Comment by olivierhagolle** [comment]
Dear William, 
I just pushed a fix which solves it. There is an inconsistency in the apihub files, the url of all tile files was changed recently, but they did not change the references within the files. I had solved the issue before for most files but had forgotten that one. 
For each url, i have to do that :
		url_header=url_header.replace("eu/odata","eu/apihub/odata")


Hope it works now. Please test and close the issue if OK.
Thanks for pointing the issue and for being patient !
Olivier

**Comment by wouellette** [comment]
Dear Olivier,

I will let you know tomorrow if the issue has been fixed on my side, and
will close the issue if so.

Cheers,

William

2016-07-31 19:16 GMT+02:00 Olivier Hagolle <notifications@github.com>:

**Comment by wouellette** [comment]
problem so

**Comment by wouellette** [comment]
Bonjour Olivier,

je vous signale jusque que la dernière mise à jour du scihub de l'esa a
sûrement dû changer le lien de téléchargement pour les données Sentinel.
Le message rendu "authorization failed", ce qui n'arrivait pas avant la
mise à jour. Je ne soulève pas de "Issue" sur Github car j'imagine que
quelqu'un le fera tôt ou tard, mais peut-être donc regarder en quoi la mise
à jour a affecté l'accès au FTP.

Merci encore.
Bonne journée,

William

2016-07-18 8:12 GMT+02:00 Olivier Hagolle <notifications@github.com>:
